perf(SmoothVisWeight): remove unnecessary loop and operate in-place.
radiocosmology/draco pull request #187
Opened 2022-08-18 18:14 UTC by ljgray

The previous implementation looped over each frequency individually.
This can be accomplished by setting the window size to 1 in the median
filter, meaning that we only need one median filter call. The filter can
also be done in-place, removing an extra memory allocation (this
probably won't change much since it's a fairly small array).

2022-09-06 21:18 UTC, jrs65 approved these changes
I'm happy to merge this as it is a cleaner, although in somes ways it seems like a sideways move as probably uses more memory. It constructs the full sized boolean array `zeromask` rather than keep it per frequency, so if there's more 4 frequencies per node this is probably more expensive memory wise (zeromask is all frequencies, 1 byte per element, versus the previous version with the intermediate 4 byte per element temporary).

2022-09-06 21:25 UTC, ljgray commented
I'm going to hold off on merging for the moment. The change I made is cleaner, but in testing there are no noticeable performance changes. This is actually quite slow overall, and is logically easily to do in parallel, so I would like to see if I can tweak it to make use of all available cores.

2022-09-27 23:49 UTC, jrs65 commented
@ljgray you probably don't need to worry about replicating the edge behaviour of the original code. I think the scheme used by the `moving_weighted_median` code (basically truncating the window at the edges) is reasonable and unbiased, and on top of that the time range pushed through the daily pipeline is deliberately padded to ensure that we don't have edges issues affecting the data we care about.

2022-09-27 23:50 UTC, ljgray commented
> @ljgray you probably don't need to worry about replicating the edge behaviour of the original code. I think the scheme used by the `moving_weighted_median` code (basically truncating the window at the edges) is reasonable and unbiased, and on top of that the time range pushed through the daily pipeline is deliberately padded to ensure that we don't have edges issues affecting the data we care about.

Ah, great.

2022-09-28 23:13 UTC, ljgray commented on draco/analysis/flagging.py
> +                size=(1, self.kernel_size),
Not sure if there's a better/more efficient way to make the weights. Maybe setting dtype to int instead of float

2022-09-28 23:45 UTC, ljgray commented
@jrs65 with the changes made in radiocosmology/caput#220, we get about a 3x performance increase with this task in the daily pipeline, and it lets us further improve the `moving_weighted_median` independently

2022-09-29 00:24 UTC, jrs65 requested changes

2022-09-29 00:24 UTC, jrs65 commented on draco/analysis/flagging.py
> +                weights=np.ones_like(weight_local[i], dtype=int),
Actually in here I think you want to take advantage of the fact it's a weighted median and weight the zero entries to zero. So it wants to be something like (
```suggestion
                weights=(weights_local[i] > 0).astype(int),
```

2022-09-29 00:25 UTC, jrs65 commented on draco/analysis/flagging.py
> +                weights=np.ones_like(weight_local[i], dtype=int),
This is obviously not what the original code does, but the input code has the issue of being biased by long regions of zero weights.

2023-03-08 18:35 UTC, merged