[WIP] hybrid beamform
radiocosmology/draco pull request #65
Opened 2019-12-13 22:24 UTC by jrs65

2021-01-11 16:58 UTC, wulfda02 approved these changes
Looks good to me!

2021-01-12 03:44 UTC, tristpinsm requested changes
Looks great! I found a few little things that might need attention.

2021-01-12 03:44 UTC, tristpinsm commented on draco/analysis/ringmapmaker.py
> +        polpair = self.telescope.polarisation[self.telescope.uniquepairs].view("U2")
very clean solution!

2021-01-12 03:44 UTC, tristpinsm commented on draco/core/containers.py
> +class HybridVisMModes(FreqContainer):
this should also be an `MContainer` right?

2021-01-12 03:44 UTC, tristpinsm commented on draco/core/containers.py
> +    _axes = ("pol", "freq", "ew", "el")
can remove `"freq"` here

2021-01-12 03:44 UTC, tristpinsm commented on draco/core/containers.py
> +        except (IndexError, ValueError):
Nice. can't count the number of times a missing `"centre"` has crashed my code...

2021-01-20 22:24 UTC, jrs65 commented on draco/analysis/ringmapmaker.py
> +                gw = (gsw[:, lfi] > 0) * ns_weight[
It's mostly in there to make sure it generates an array of the right shape.

2021-01-21 05:15 UTC, merged